### ISSUE TITLE
Windows error JGitEnvironmentRepository fails to delete .git\objects\*pack

### ISSUE THREAD

**Issue by jgolubenko** [spring-cloud/spring-cloud-config#293]
I am trying to pull git repo from bitbucket for our @EnableConfigServer app, but it  fails in this method:  `JGitEnvironmentRepository.deleteBaseDirIfExists()`. 

While it might not be exactly spring-cloud-config's problem, because internally it calls eclipse.jgit.* library, but has anyone came across this before?

I've tried to start from eclipse/sts, from cygwin and cmd as Administrator. (I haven't tried it on Ubuntu yet, but will do in couple hours). 

`basedir` configuration property makes no difference apart from checking out in temp dir or under path relative to my app, still the same error.

my application.yml

```
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://www.bitbucket.org/myrepo/ms-configuration
          password: pass
          username: user
          clone-on-start: true
          # basedir: cloud-config/ # if I enable this, makes no difference
```

Exception that is thrown upon startup:

```
Caused by: java.io.IOException: Could not delete file C:\cygwin\tmp\config-repo-7024054885475694217\.git\objects\pack\pack-59244256763eca9b6add9057d20587530bf2001a.pack
        at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:197) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
        at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:164) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
        at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:166) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
        at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:166) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
        at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:166) ~[org.eclipse.jgit-4.1.1.201511131810-r.jar:4.1.1.201511131810-r]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.deleteBaseDirIfExists(JGitEnvironmentRepository.java:280) ~[spring-cloud-config-server-1.1.0.M3.jar:1.1.0.M3]
        ... 34 common frames omitted
```

Please note I've upgraded jgit to org.eclipse.jgit to `4.1.1.201511131810-r` from default `3.5.3.201412180710-r` hoping it would resolve this.

Exception is thrown here: `org.springframework.cloud.config.server.environment.JGitEnvironmentRepository`

```
	private void deleteBaseDirIfExists() {
		if (getBasedir().exists()) {
			try {
				FileUtils.delete(getBasedir(), FileUtils.RECURSIVE);
			}
			catch (IOException e) {
				throw new IllegalStateException("Failed to initialize base directory", e);
			}
		}
	}
```
which in my case resides in  `spring-cloud-config-server-1.1.0.M3.jar`

Any ideas?

Thank you!

**Comment by dsyer** [comment]
Looks like probably a Windows-specific issue, so it would be useful if you can try it on a different OS. Or provide a sample project that fails. Or both.

**Comment by jgolubenko** [comment]
Here is the link to bare bones project that fails https://github.com/jgolubenko/ms-server-config-demo

**Comment by jgolubenko** [comment]
Update: above mentioned project is working on CentOS 7 I can confirm. So this looks like a Windows issue (don't have Mac to try).

**Comment by jgolubenko** [comment]
Dave, I've also noticed that you replied to this thread before (about a year ago): http://stackoverflow.com/questions/26985843/spring-config-server-does-not-refresh-properties and it looks like it's related to 'cannot delete' on windows as well. I'm curious as to why this issue doesn't seem to have any attention. I understand that most people these days run linux/macs (and I do as well where I can) but for development in corporate environment sometimes win is enforced :>

**Comment by spencergibb** [comment]
@jgolubenko is the a problem you're having in production?

**Comment by jgolubenko** [comment]
@spencergibb not in production, we are running centos in prod, so that would not be a problem there, since I've tested it on *nix and it works fine. But in development we are forced to use windows so it's quite an issue.

**Comment by dsyer** [comment]
We fixed a bunch of issues (probably about a year ago), so I wouldn't say it's fair to say this issue gets no attention. We don't run CI builds (or any tests regularly) on Windows though, so issues do creep in. If you are in a position to fix it please send a PR.

**Comment by t4gedieb** [comment]
Windows creates a file lock at org.eclipse.jgit.internal.storage.file.PackFile:601 by createing a Random AccessFile reference and prevents deleting the base dir.
If there is an existing git client it must be closed before deleting the base dir.

https://github.com/spring-cloud/spring-cloud-config/pull/309

**Comment by dsyer** [comment]
I can't see how there could be an unclosed git client. I'm going to assume this was fixed in c97a8f51. If anyone can reproduce it still please shout.

**Comment by t4gedieb** [comment]
Unfortunately the bug still persists.  c97a8f51446fc8ff5558b6a085cb394324932b99 didn't fix the problem.

I could track back the problem to an open RandomAccessFile created at <code>org.eclipse.jgit.internal.storage.file.PackFile:601</code>. To close this file it is required to close the Git client returned by <code>org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir()</code>. Not closing the file will lock the file on Windows systems to the Java process and prevent it from being deleted.

**Comment by dsyer** [comment]
How about 3f77d80? Is that better? I cherry picked it onto 1.1.0.M4 as well (and re-deployed it, so you need to clear your caches if you already used it).

**Comment by t4gedieb** [comment]
This fix works great!

But there is another file lock problem on Windows. The ResourceController doesn't close the inputstreams and creates file locks. See proposed solution #315

**Comment by dl1ely** [comment]
@t4gedieb Can you give me a hint how to identify those opened streams/locked files? In tests for spring-cloud-server i have the same issue, in https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/test/ConfigServerTestUtils.java#L73 a pack file cannot be deleted as it is locked by another process on windows, making tests fail on windows only. Unfortunately i have no idea how to find the offender. Thank you.

**Comment by t4gedieb** [comment]
I used Unlocker 1.9.0, but don't know if it still exists. you can probably also use Windows Explorer https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

-------- Original message --------

**Comment by dl1ely** [comment]
@t4gedieb Thanks, but that will only show the windows process? I am pretty sure this will be `java.exe`. How did you pinpoint the exact locations in the source where this locking/keep open stuff happens? Just by looking at the source? Right now, i do not even know where to look for a start.

**Comment by t4gedieb** [comment]
Yes, I was debugging the code and looking for Input- and Outputstreams which are not properly closed

-------- Original message --------

**Comment by ericis** [comment]
This bug still happens on Windows

**Comment by dsyer** [comment]
Which bug? This issue is closed and a fix was applied. Is there something else broken? Please provide details and/or open a new issue (or even better send a pull request).

**Comment by SumitBhawsar** [comment]
I am still facing the same issue in both windows and in unix.

Initially I thought it is a different problem but after debug I found the issue is because of not able to delete a *.pack file. 

Raised a new bug with the steps 
https://github.com/spring-cloud/spring-cloud-config/issues/1109

**Comment by abhishar03** [comment]
I am unable to do mvn clean install more than 84 tests failing all mostlyrelated unable to delete .pack

**Comment by prabhukvn** [comment]
Most probably turbine stream is the culprit, remove turbine and check once.

**Comment by spencergibb** [comment]
Turbine stream is unrelated and would not have any effect
