### ISSUE TITLE
ResourceController not loaded after upgrade to version 1.2.0.RELEASE

### ISSUE THREAD

**Issue by tschlegel** [spring-cloud/spring-cloud-config#524]
After upgrading from version 1.1.3 to version 1.2.0.RELEASE (by changing Spring Cloud dependencies from Brixton.SR5 to Camden.RELEASE), the ResourceController is not instantiated and thus plain text files don't work.

I analysed the problem and found that Bean `resourceRepository` in class `ResourceRepositoryConfiguration` is not instantiated because the annotation `@ConditionalOnBean(SearchPathLocator.class)` cannot find the bean. When I changed the condition to `@ConditionalOnBean(name = "environmentRepository")` the issue is fixed.

**Comment by ryanjbaxter** [comment]
When you say plain test files don't work, are you referring to returning configuration as plain text?

**Comment by spencergibb** [comment]
This is fixed on master. See b8278772837ad60a1db9d658e7a8ef4f33b80732

**Comment by tschlegel** [comment]
Hi, I have updated the config server to version 1.2.1.RELEASE and I am still facing the same issue that I cannot use plain text resources from the config server. 

The `ResourceRepository` bean in class `org.springframework.cloud.config.server.config.ResourceRepositoryConfiguration` is not getting instanciated despite changing the bean types in `EnvironmentRepositoryConfiguration`.

**Comment by spencergibb** [comment]
@tschlegel see #530 1.2.2 was released yesterday with Camden.SR2

**Comment by spencergibb** [comment]
@tschlegel I meant snapshots, it wasn't part of SR2
